---
- name: set hostname
  hostname: 
    name: "{{inventory_hostname}}"
- name: subscribe to redhat
  redhat_subscription:
    state: present
    force_register: false
    username: "{{subscription_user}}"
    password: "{{subscription_password}}"
    pool_ids: "{{subscription_pool}}"
- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled
- name: enable required repos
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
    - "rhel-7-server-rpms"
    - "rhel-7-server-extras-rpms"
    - "rhel-7-server-ose-3.11-rpms"
    - "rhel-7-server-ansible-2.6-rpms"
- name: install prereq packages
  yum:
    name:
      - wget 
      - git
      - net-tools 
      - bind-utils 
      - yum-utils 
      - iptables-services 
      - bridge-utils 
      - bash-completion 
      - kexec-tools 
      - sos 
      - psacct
      - openshift-ansible 
      - docker-1.13.1
    state: present 
- name: upgrade all packages
  yum: name=* state=latest
- name: Create .ssh folder
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700
- name: Upload root SSH public authorized key
  copy:
    src:  /root/.ssh/id_rsa.pub
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: "0600"
